config/routes.rb
Rails.application.routes.draw do

  get '/categories/index' =>'categories#index', as: 'categories'
  get '/categories/:id' => 'categories#show', as: 'category'

  root 'pages#index'
  get 'pages/index' => 'pages#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/projects/find_pledge' => 'projects#z_find_pledge', as: 'custom_find_pledge'

  resources :users

  resources :projects do
    resources :pledges, only: [:new, :create]
  end

  resources :pledges, only: [:index, :show, :edit, :update, :destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  name            :string
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  # Validations
  validates :name, :email, presence: true
  validates :password, length: { minimum: 6, allow_blank: true }

  # Associations
  has_secure_password
  has_many :projects, dependent: :destroy
  has_many :pledges, dependent: :destroy
  # has_many :assigned_pledges, :through => :projects, :table_name => "pledges"

  # Logic
  def projects_pledges_sum
    if self.projects.length > 0
      # Use map to return an array of project pledges
      project_pledges = self.projects.map do |p|
        p.pledges
      end
      # Flatten the array and then use reduce to return the total sum amount
      project_pledges.flatten!.reduce(0) do |sum, pledge|
        sum + pledge.amount
      end
    else
      0
    end
  end

  def bank_left
    self.bank - self.pledges.sum(:amount) + self.projects_pledges_sum
  end

  def can_pledge?( amount )
    self.bank_left >= amount.to_i
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, :only => [:index, :edit]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if params[:file]
      req = Cloudinary::Uploader.upload(params[:file])
      @user.image = req["public_id"]
    else
      @user.image = 'placeholder_y6he4n'
    end

    if @user.save
      flash[:success] = "User created"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if params[:file]
      req = Cloudinary::Uploader.upload(params[:file])
      @user.image = req["public_id"]
    else
      @user.image = 'placeholder_y6he4n'
    end

    if @user.save
      flash[:success] = "User updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :image, :password_confirmation)
    end

    def require_login
      unless @current_user.present?
        # For redirecting to intended url. Save the request.url in a session
        session[:intended_url] = request.url
        flash[:error] = "You must be logged in to access this page"
        redirect_to login_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def own_user?
    @user == @current_user
  end

  def format_bank(user)
      number_to_currency(user.bank_left, precision: 0)
  end

  def format_pledges_received(user)
    number_to_currency(user.pledges.sum(:amount), precision: 0)
  end

  def format_session_user
    if @current_user
      link_to "@current_user: #{@current_user.name.titleize} logged in with bank funds of #{format_bank(@current_user)}", user_path(@current_user)
    else
      "Login above"
    end
  end

end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <fieldset>
    <%= render "shared/errors", object: @user %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.label "Avatar image upload" %><br>
      <%= f.cl_image_upload :image %>
    </p>
    <p>
      <%= f.submit :class => 'btn'%>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>User Edit: <%= @user.name %></h1>
<%= render :partial => "form" %>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |el| %>
    <li><%= link_to el.name, user_path(el) %></li>
  <% end  %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1>User: <%= @user.name %></h1>

<!-- User -->
<hr>
<h3><%= @user.name.titleize %> account summary:</h3>
<div class="row">
  <div class="col s12 m4 center-align">
    <%= cl_image_tag(@user.image, :width => 200, :height => 200, :effect => "pixelate_faces:7", :crop => :fill) %>
  </div>
  <div class="col s12 m8">
    <table class="striped">
      <tr>
        <td>Name:</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td>Member since:</td>
        <td><%= time_ago_in_words(@user.created_at) %> ago</td>
      </tr>
      <tr>
        <td>All projects:</td>
        <td><%= @user.projects.count %></td>
      </tr>
      <tr>
        <td>All project goal:</td>
        <td><%= number_to_currency(@user.projects.sum(:target_amount), precision: 0) %></td>
      </tr>
      <tr>
        <td>Bank opening:</td>
        <td><%= number_to_currency(@user.bank, precision: 0) %></td>
      </tr>
      <tr>
        <td>&nbsp; Pledges received:</td>
        <td>+ <%= number_to_currency(@user.projects_pledges_sum, precision: 0) %></td>
      </tr>
      <tr>
        <td>&nbsp; Pledges made:</td>
        <td>- <%= format_pledges_received(@user) %></td>
      </tr>
      <tr>
        <td>Bank closing:</td>
        <td>= <%= format_bank(@user) %></td>
      </tr>
      <% if own_user? %>
      <tr>
        <td>Controls:</td>
        <td>
          <%= link_to 'Edit', edit_user_path(@user) %> |
          <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </table>
</div>
<hr>
<!-- User Project -->
<h3><%= @user.name.titleize %> project summary:</h3>
<%= link_to "Start your new project", new_project_path, :class => 'btn' %><br>

<% if @user.projects.length > 0 %>
  <table class="responsive-table striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Target</th>
        <th>Pledged</th>
        <th>Status</th>
        <th>Deadline</th>
        <th>Backers</th>
        <th>Categories</th>
        <% if own_user? %>
          <th>Controls</th>
        <% end %>
      </tr>
    </thead>
    <% @user.projects.order('target_amount desc').each do |el| %>
      <tr>
        <td><%= link_to el.name, project_path(el) %></td>
        <td><%= format_description(el) %></td>
        <td><%= format_target(el) %></td>
        <td><%= format_pledged(el) %></td>
        <td><%= format_goal(el) %></td>
        <td><%= format_deadline(el) %></td>
        <td><%= format_backers(el) %></td>
        <td>
          <% el.categories.each do |el| %>
            <%= link_to "#{el.name.titleize}", category_path(el) %>
          <% end %>
        </td>
        <% if own_user? %>
          <td>
            <%= link_to 'Edit', edit_project_path(el) %> |
            <%= link_to 'Delete', project_path(el), method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<hr>
<!-- User Pledges -->
<h3><%= @user.name.titleize %> pledge summary:</h3>
<%= link_to "Back a new project", custom_find_pledge_path, :class => 'btn' %><br>
<% if @user.pledges.length > 0 %>

<table class ="responsive-table striped">
  <thead>
    <tr>
      <th>Backed</th>
      <th>Your pledge</th>
      <th>Project description</th>
      <th>Your comment</th>
      <th>Author</th>
      <% if own_user? %>
        <th>Controls</th>
      <% end %>
    </tr>
  </thead>
  <% @user.pledges.order('amount desc').each do |el| %>
    <% if el.project %>
    <tr>
      <td>
        <%= link_to el.project.name, project_path(el.project) %>
      </td>
      <td><%= format_pledged(el.project) %></td>
      <td><%= format_description(el.project) %></td>
      <td>"<%= el.comment %>"</td>
      <td><%= link_to el.project.user.name, user_path(el.project.user) %></td>
      <% if own_user? %>
        <td>
          <%= link_to 'Edit', edit_pledge_path(el) %> |
          <%= link_to 'Delete', pledge_path(el), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      <% end %>
    </tr>
    <% end %>
  <% end %>
</table>
<% end %>