config/routes.rb
Rails.application.routes.draw do

  get '/categories/index' =>'categories#index', as: 'categories'
  get '/categories/:id' => 'categories#show', as: 'category'

  root 'pages#index'
  get 'pages/index' => 'pages#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/projects/find_pledge' => 'projects#z_find_pledge', as: 'custom_find_pledge'

  resources :users

  resources :projects do
    resources :pledges, only: [:new, :create]
  end

  resources :pledges, only: [:index, :show, :edit, :update, :destroy]

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  name          :string
#  description   :text
#  target_amount :decimal(, )
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Project < ActiveRecord::Base
  # Validations
  validates :name, presence: true
  validates :description, length: {minimum: 10}
  validates :target_amount, numericality: {greater_than: 0, less_than_or_equal_to: 10000}
  validates :deadline, presence: true

  # Associations
  belongs_to :user
  has_many :pledges, dependent: :destroy
  has_and_belongs_to_many :categories

  # Logic
  def sort_pledges
    pledges.order('amount desc')
  end

  def pledge_sum
    self.pledges.sum(:amount)
  end

  def target_shortfall
    self.target_amount - pledge_sum
  end

  def pledges?
    pledge_sum > 0
  end

  def shortfall?
    target_shortfall > 0
  end

  def target_percent
    (pledge_sum / self.target_amount) * 100
  end

  def target_surplus
    pledge_sum - self.target_amount
  end

  def expired?
    self.deadline < Time.now
  end

  def self.live_projects
    self.select do |el|
      el.expired? == false
    end
  end

  def order_pledges
    pledges.order('amount desc')
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, :only => [:new, :edit]

  def z_find_pledge
    @projects = Project.all
  end

  def index
    @projects = Project.all.sort_by do |project|
      project.pledge_sum
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    # This is the magic stuff that will let us upload an image to Cloudinary when creating a new project.
    # HM!! Remember that we have to reference :file in the params as the cl form_for helper renders in html name="file" so we are pulling the file from params[:file] and then storying the Cloudinary url equivalent in the image tag

    @project = @current_user.projects.create(project_params)
    # Note that Cloudinary assigns each image a unique public_id which we pass as the url to be modified and transformed with the Cloudinary app
    if params[:file]
      req = Cloudinary::Uploader.upload(params[:file])
      @project.image = req["public_id"]
    else
      @project.image = 'placeholder_y6he4n'
    end

    if @project.save
      flash[:success] = "New project created"
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = @current_user.projects.find(params[:id])
  end

  def update
    @project = @current_user.projects.find(params[:id])

    @project.update(project_params)
    if params[:file]
      req = Cloudinary::Uploader.upload(params[:file])
      @project.image = req["public_id"]
    else
      @project.image = 'placeholder_y6he4n'
    end

    if @project.save
      flash[:success] = "Project updated"
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = @current_user.projects.find(params[:id])
    @project.destroy
    flash[:success] = "Project deleted"
    redirect_to user_path(@current_user)
  end

  private
    def project_params
      params.require(:project).permit(:name, :description, :target_amount, :deadline, :bank,  {category_ids: []})
    end

    def require_login

      unless @current_user.present?
        # For redirecting to intended url. Save the request.url in a session
        session[:intended_url] = request.url
        flash[:error] = "You must be logged in to access this page"
        redirect_to login_path
      end

    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_backers(project)
    pluralize(project.pledges.count, 'backer')
  end

  def format_target(project)
    number_to_currency(project.target_amount, precision: 0)
  end

  def format_pledged(project)
    number_to_currency(project.pledge_sum, precision: 0)
  end

  def format_percent(project)
    number_to_percentage(project.target_percent, precision: 0)
  end

  def format_shortfall(project)
    if project.shortfall?
      "#{number_to_currency(project.target_shortfall, precision: 0)} shortfall"
    else
      "Fully funded!"
    end
  end

  def format_status(project)
    unless project.expired?
      format_shortfall(project)
    else
      "Expired"
    end
  end

  def format_goal(project)
    unless project.expired?
      "#{format_percent(project)} funded of #{format_target(project)} goal"
    else
      "Expired"
    end
  end

  def format_deadline(project)
    if project.deadline > Time.now
      "#{time_ago_in_words(project.deadline).capitalize} to go"
    else
      "#{time_ago_in_words(project.deadline).capitalize} overdue"
    end
  end

  def format_project_expired(project)
    "#{project.name} expired #{time_ago_in_words(project.deadline)} ago, no more pledges"
  end

  def format_description(project)
    truncate(project.description, length: 45, separator: ' ')
  end

  def format_image_tag(project)
    cl_image_tag(project.image, :width => 150, :height => 200, :crop => :fit)
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:multipart => true}) do |f| %>
  <fieldset>
    <%= render "shared/errors", object: @project %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :target_amount, "Target amount (up to $10,000)" %><br>
      <%= f.number_field :target_amount, max: 10000 %>
    </p>
    <p>
      <%= f.label :deadline, "Deadline (up to 6 months)" %><br>
      <%= f.date_field :deadline, min: Date.today, max: (Date.today + 6.months) %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, cols: 40, rows: 7 %>
    </p>
    <p>
      <%= f.label "Project image upload" %><br>
      <%= f.cl_image_upload :image %>
    </p>
    <p>Select categories:</p>
    <p>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </p>
    <p>
      <%= f.submit :class => 'btn'%>
    </p>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit your Project</h1>
<%= render :partial => 'form'  %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<% if @current_user %>
  <%= link_to "New project", new_project_path, :class => "btn" %>
<% else %>
  <%= link_to "Join the fun, start a new Project", new_project_path, :class => "btn" %>
<% end %>
<hr>
<%= render "shared/project", object: @projects %>

app/views/projects/new.html.erb
<h1>Create new Project</h1>
<%= render :partial => 'form'  %>

app/views/projects/show.html.erb
<% unless check_project(@project) %>
  <h1><%= "#{@project.name} by #{@project.user.name}" %></h1>
<% else %>
  <h1>Your project: <%= @project.name %></h1>
<% end %>

<% unless check_project(@project) %>
  <% if check_pledge(@project) %>
    <%= link_to "You have pledged to this Project", pledge_path(@current_user.pledges.find_by(:project_id => @project.id)), :class => 'btn green' %>
  <% elsif @project.expired? %>
    <%= format_project_expired(@project) %>
  <% elsif @project.pledges? %>
    <%= link_to "Back this project", new_project_pledge_path(@project), :class => 'btn' %>
  <% else %>
    <%= link_to "Be the first to back this project", new_project_pledge_path(@project), :class => 'btn' %>
  <% end %>
<% end %>
<hr>

<div class="row">

  <div class="col m4 s12 center-align">
    <%= cl_image_tag(@project.image, :width => 300, :height => 300, :crop => :fill)%>
  </div>
  <div class="col s12 m8">
    <table class="striped">
      <tr>
        <td>Name:</td>
        <td><%= @project.name %></td>
      </tr>
      <tr>
        <td>Creator:</td>
        <td><%= link_to @project.user.name, user_path(@project.user) %></td>
      </tr>
      <tr>
        <td>Target amount:</td>
        <td><%= format_target(@project) %></td>
      </tr>
      <tr>
        <td>Time remaining:</td>
        <td><%= format_deadline(@project) %></td>
      </tr>
      <tr>
        <td>Description:</td>
        <td><%= @project.description %></td>
      </tr>
      <tr>
        <td>Categories:</td>
        <td>
          <% @project.categories.each do |el| %>
            <%= link_to "#{el.name.titleize}", category_path(el) %> &nbsp;
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Created:</td>
        <td><%= format_created(@project) %></td>
      </tr>
      <tr>
        <td>Last updated:</td>
        <td><%= format_updated(@project) %></td>
      </tr>
      <% if check_project(@project) %>
        <tr>
          <td>Controls:</td>
          <td>
            <div class="controls">
              <%= link_to 'Edit', edit_project_path(@project) %> |
              <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<hr>

<h3>Pledge summary:</h3>

<% if check_project(@project) || @project.pledges? %>

  <table class= "striped">
    <tr>
      <td>Status:</td>
      <td><%= format_shortfall(@project) %></td>
    </tr>
    <tr>
      <td>Goal:</td>
      <td><%= format_goal(@project) %></td>
    </tr>
    <tr>
      <td>Backers:</td>
      <td><%= "#{format_pledged(@project)} pledged by #{format_backers(@project)}:" %>
        <ul>
          <% @project.order_pledges.each do |pledge| %>
            <li><%= "#{number_to_currency(pledge.amount, precision: 0)} from "%><%= link_to pledge.user.name, user_path(pledge.user) %></li>
          <% end %>
        </ul>
    </td>
    </tr>
  </table>
<% else %>
  <p>Awaiting pledges</p>
<% end %>

app/views/projects/z_find_pledge.html.erb
<h1>Back a new project</h1>
<ul>
  <% @projects.each do |el| %>
    <% unless check_project(el) %>
      <% if check_pledge(el) %>
        <li><%= link_to "#{el.name} by #{el.user.name} (You backed this project!!)", project_path(el) %></li>
      <% else %>
        <li><%= link_to "#{el.name} by #{el.user.name}", project_path(el) %></li>
      <% end %>
    <% end %>
  <% end %>
</ul>