config/routes.rb
Rails.application.routes.draw do

  get '/categories/index' =>'categories#index', as: 'categories'
  get '/categories/:id' => 'categories#show', as: 'category'

  root 'pages#index'
  get 'pages/index' => 'pages#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/projects/find_pledge' => 'projects#z_find_pledge', as: 'custom_find_pledge'

  resources :users

  resources :projects do
    resources :pledges, only: [:new, :create]
  end

  resources :pledges, only: [:index, :show, :edit, :update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fundie</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  
</head>
<body>
  <header>
  <nav>
    <div class="nav-wrapper">
      <div class="container">
      <a href="/" class="brand-logo center hide-on-small-only">Fundie</a>

      <ul id="nav-mobile" class="left">
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Pledges", pledges_path %></li>
      </ul>

      <ul id="nav-mobile" class="right">
        <% if @current_user %>
          <li><%= link_to "View account", user_path(@current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "New user", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
  </header>

  <main>

  <div class="container">

    <!-- APP SUMMARY -->
    <div class="card-panel teal lighten-2">
      <%= format_app_summary %>
    </div>

    <!-- Session id -->
    <p class="right-align"><em><%= format_session_user %></em></p>

    <!-- FLASH MESSAGE -->
    <% if flash[:success] %>
      <p><%= flash[:success] %></p>
    <% end %>
    <% if flash[:error] %>
      <p><%= flash[:error] %></p>
    <% end %>

    <%= yield %>
  </div>

  </main>

  <footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Acknowledgements</h5>
        <p class="grey-text text-lighten-4">Ruby on Rails project by Howie Mann as part of GA WDi16 Project One. Project inspiration from Kickstarter.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Discover</h5>
        <ul>
          <li><%= link_to "All categories", categories_path, :class => "grey-text text-lighten-3" %></li>
          <li><%= link_to "All projects", projects_path, :class => "grey-text text-lighten-3" %></li>
          <li><%= link_to "Pledge rank", pledges_path, :class => "grey-text text-lighten-3" %></li>
          <li><%= link_to "New project", new_project_path, :class => "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Howie_Burger. Find me on <a href="http://www.github.com/howardmann" target="_blank">GitHub</a>
    </div>
  </div>
</footer>

</body>
</html>